version: "3"
services:
    web:
        image: isaackuang/openresty:1.11.0
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        links:
            - redis
    redis:
        image: redis
